;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-babel-insert-hyphen
        LaTeX-insert-left-brace
        TeX-insert-backslash
        backward-sexp
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        forward-sexp
        gdb-delchar-or-quit
        increment-number-at-point
        isearch-forward-regexp
        isearch-printing-char
        kill-region
        mark-sexp
        my-exchange-point-and-mark
        ))

(setq mc/cmds-to-run-once
      '(
        isearch-delete-char
        ))
